addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

const links = [
  {
  "name": "My LinkedIn Profile",
  "url" : "https://www.linkedin.com/in/narendramohanm/"
  },

  {
    "name": "My GitHub Account",
    "url" : "https://github.com/Narendramohanm"
  },

  {
    "name": "CloudFlare Project on GitHub",
    "url" : "https://github.com/Narendramohanm/CloudFlare-Coding-Challenge"
  }
]

async function handleRequest(request) {

  const url = request.url

  if(url.indexOf("/links") != -1){
    const jsonData = JSON.stringify(links, null, 2)

    return new Response(jsonData, {
      headers: {
        "content-type": "application/json;charset=UTF-8"
      }
    })
  }
  else{
    const html = `<!DOCTYPE html>
      <body>
        <h1>Hello World</h1>
        <p>This markup was generated by a Cloudflare Worker.</p>
        <p>This is not /links<p>
      </body>`

      return new Response(html, {
        headers: {
          "content-type": "text/html;charset=UTF-8",
        },
      })
    }

}
  
